name: Generate Snake

on:
  schedule: # Run workflow every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: shibbu04  # Your GitHub username
          outputs: dist/snake.svg
      - name: Upload Snake SVG
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/snake.svg
