name: Generate Snake

on:
  schedule: # Runs the workflow daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: shibbu04  # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Upload the snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/snake.svg
